# Generated by Django 2.1.4 on 2019-02-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='fname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='lname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reg',
            name='mobile',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
